from typing import Final

VAR_DOMINO_ENV: Final[str] = "DOMINO_ENV"
VAR_DOMINO_UNITTEST_MODE: Final[str] = "DOMINO_UNITTEST_MODE"
VAR_DOMINO_MAX_THREADS_BUILD_TASK: Final[str] = "DOMINO_MAX_THREADS_BUILD_TASK"
VAR_DOMINO_MAX_THREADS_BUILD_TASKGROUP: Final[str] = (
    "DOMINO_MAX_THREADS_BUILD_TASKGROUP"
)
