name: domino
services:
  airflow:
    image: airflow-3.x.x-standalone-local
    container_name: airflow-3.x.x-dev
    build:
      context: ..
      dockerfile: .container/Dockerfile
      args:
        AIRFLOW_VERSION: ${AIRFLOW_VERSION:-3.2.0}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11}
    ports:
      - "8080:8080"
    command: [ "airflow", "standalone" ]
    environment:
      AIRFLOW_HOME: "/opt/airflow"
      AIRFLOW_CONFIG: "/opt/airflow/airflow.cfg"
      AIRFLOW_ENV: "${AIRFLOW_ENV:-dev}"
      AIRFLOW__API_AUTH__JWT_SECRET: "${AIRFLOW__API_AUTH__JWT_SECRET:-}"
      PYTHONPATH: "/opt/airflow/domino:${PYTHONPATH:-}"
      # Google Cloud
      GOOGLE_APPLICATION_CREDENTIALS: "/opt/airflow/keys/application_default_credentials.json"
      GOOGLE_CLOUD_PROJECT: "${GOOGLE_CLOUD_PROJECT:-}"
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: "google-cloud-platform://?project=${GOOGLE_CLOUD_PROJECT:-}"
      # Kubernetes
      KUBECONFIG: "/opt/airflow/.kube/config"
      AIRFLOW_CONN_KUBERNETES_DEFAULT: "kubernetes://?kube_config_path=%2Fopt%2Fairflow%2F.kube%2Fconfig&"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/.container/airflow.standalone.v3.cfg:/opt/airflow/airflow.cfg
      - ${AIRFLOW_PROJ_DIR:-.}/.container/airflow_local_settings.v3.py:/opt/airflow/config/airflow_local_settings.py
      - ${AIRFLOW_PROJ_DIR:-.}/domino:/opt/airflow/domino
      - ${AIRFLOW_PROJ_DIR:-.}/simple_auth_manager_passwords.json.generated:/opt/airflow/simple_auth_manager_passwords.json.generated
      - ${GOOGLE_APPLICATION_CREDENTIALS:-~/.config/gcloud/application_default_credentials.json}:/opt/airflow/keys/application_default_credentials.json:ro
      - ${KUBECONFIG:-~/.kube/config}:/opt/airflow/.kube/config:ro
